[package]
name = "rebels"
version = "1.0.14"
edition = "2021"

[profile.release]
strip = true
opt-level = 3

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
chrono = "0.4.34"
clap = { version = "4.5.0", features = ["derive"] }
crossterm = "0.26.1"
directories = "5.0.1"
ed25519-dalek = "2.1.1"
futures = "0.3.30"
gif = "0.12.0"
image = "0.24.8"
imageproc = "0.23.0"
include_dir = "0.7.3"
itertools = "0.11.0"
libp2p = { version = "0.52.4", features = [
    "noise",
    "ping",
    "tcp",
    "tokio",
    "yamux",
    "gossipsub",
    "mdns",
    "macros",
    "serde",
] }
log = "0.4.21"
log4rs = { version = "1.3.0", features = ["file_appender", "pattern_encoder"] }
once_cell = "1.19.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
ratatui = { version = "0.27.0", features = ["all-widgets"] }
rodio = "0.18.1"
russh = "0.43.0"
russh-keys = "0.43.0"
serde = { version = "1.0.196", features = ["derive", "default"] }
serde_json = "1.0.113"
serde_repr = "0.1.18"
sha2 = "0.10.8"
stream-download = { version = "0.7.0", features = ["reqwest-rustls"] }
strum = { version = "0.21", features = ["derive"] }
strum_macros = "0.25.3"
tokio = { version = "1.37.0", features = ["full"] }
tui-textarea = "0.5.1"
unicode-width = "0.1.11"
url = "2.5.2"
uuid = { version = "1.7.0", features = ["v4", "serde"] }
void = "1.0.2"
