[package]
name = "rebels"
version = "1.0.19"
edition = "2021"

[profile.release]
strip = true
opt-level = 3

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
anyhow = "1.0.91"
async-trait = "0.1.83"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
directories = "5.0.1"
ed25519-dalek = "2.1.1"
futures = "0.3.30"
gif = "0.13.1"
glam = "0.29.0"
image = "0.25.4"
imageproc = "0.25.0"
include_dir = "0.7.4"
itertools = "0.13.0"
libp2p = { version = "0.52.4", features = [
    "noise",
    "ping",
    "tcp",
    "tokio",
    "yamux",
    "gossipsub",
    "mdns",
    "macros",
    "serde",
] }
log = "0.4.22"
log4rs = { version = "1.3.0", features = ["file_appender", "pattern_encoder"] }
once_cell = "1.20.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
ratatui = { version = "0.29.0", features = ["unstable-backend-writer"] }
rodio = "0.19.0"
russh = "0.45.0"
russh-keys = "0.45.0"
serde = { version = "1.0.212", features = ["derive", "default"] }
serde_json = "1.0.132"
serde_repr = "0.1.19"
sha2 = "0.10.8"
stream-download = { version = "0.9.0", features = ["reqwest-rustls"] }
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.26.4"
tokio = { version = "1.41.0", features = ["full"] }
tokio-util = "0.7.12"
tui-textarea = "0.7.0"
unicode-width = "0.2.0"
url = "2.5.2"
uuid = { version = "1.11.0", features = ["v4", "serde"] }
void = "1.0.2"
