[package]
name = "rebels"
version = "1.0.8"
edition = "2021"

[profile.release]
strip = true
opt-level = 3

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
uuid = { version = "1.7.0", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "serde",
] }
crossterm = "0.26.1"
rand = "0.8.5"
ratatui = { version = "0.26.2", features = ["all-widgets"] }
strum = { version = "0.21", features = ["derive"] }
image = "0.24.8"
gif = "0.12.0"
serde_json = "1.0.113"
serde = { version = "1.0.196", features = ["derive", "default"] }
rand_distr = "0.4.3"
strum_macros = "0.25.3"
itertools = "0.11.0"
futures = "0.3.30"
libp2p = { version = "0.52.4", features = [
    "noise",
    "ping",
    "tcp",
    "tokio",
    "yamux",
    "gossipsub",
    "mdns",
    "macros",
    "serde",
] }
tokio = { version = "1.36.0", features = ["full"] }
tui-textarea = "0.4.0"
void = "1.0.2"
directories = "5.0.1"
rand_chacha = "0.3.1"
serde_repr = "0.1.18"
clap = { version = "4.5.0", features = ["derive"] }
include_dir = "0.7.3"
once_cell = "1.19.0"
imageproc = "0.23.0"
rodio = "0.17.3"
chrono = "0.4.34"
unicode-width = "0.1.11"
russh = { git = "https://github.com/warp-tech/russh" }
russh-keys = { git = "https://github.com/warp-tech/russh" }
async-trait = "0.1.77"
ed25519-dalek = "2.1.1"
anyhow = "1.0.79"
log = "0.4.21"
log4rs = { version = "1.3.0", features = ["file_appender", "pattern_encoder"] }
